'use strict';
(()=>{
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 const a=(url,text)=>{const n=el('a',text);try{const u=new URL(url,location.href);if(!['https:','http:','file:'].includes(u.protocol))return n;n.href=u.href;if(u.origin!==location.origin){n.target='_blank';n.rel='noopener noreferrer'}}catch{}return n};
 const metrics=document.getElementById('economyData');
 if(metrics){metrics.replaceChildren();for(const r of window.GERMANY_ECONOMY?.metrics||[]){const b=el('div',undefined,'metric');b.append(el('h3',r.label),el('strong',Number(r.value).toLocaleString('ja-JP',{maximumFractionDigits:2})+' '+r.unit),el('small','対象：'+r.period+' ／ 確認：'+r.checkedOn),el('p',r.note),a(r.source,'公式出典 ↗'));metrics.append(b)}if(!metrics.children.length)metrics.append(el('p','統計の取得準備中です。公式情報源をご確認ください。'))}
 const rankRows=document.getElementById('rankRows');
 if(rankRows){const data=window.GERMANY_RANKINGS||{records:[],coverage:''}, search=document.getElementById('rankSearch'),provider=document.getElementById('rankProvider'),subject=document.getElementById('rankSubject'),year=document.getElementById('rankYear');document.getElementById('rankingCoverage').textContent=data.coverage;
 [...new Set(data.records.map(r=>r.subject))].filter(s=>s!=='総合').sort().forEach(s=>subject.add(new Option(s,s)));
 [...new Set(data.records.map(r=>r.year))].sort((a,b)=>b-a).forEach(y=>year.add(new Option(String(y),String(y))));const render=()=>{let rows=data.records.filter(r=>(!year.value||String(r.year)===year.value)&&(!provider.value||r.provider===provider.value)&&r.subject===subject.value&&r.university.toLowerCase().includes(search.value.trim().toLowerCase()));rows.sort((a,b)=>b.year-a.year||parseInt(a.rank.replace('=',''))-parseInt(b.rank.replace('=',''))||a.university.localeCompare(b.university));rankRows.replaceChildren();for(const r of rows){const tr=el('tr');tr.append(el('td',r.university),el('td',r.provider+' '+r.year),el('td',r.subject),el('td',r.rank));const td=el('td');td.append(a(r.source,'出典 ↗'),el('small',' 確認 '+r.checkedOn));tr.append(td);rankRows.append(tr)}document.getElementById('rankCount').textContent=rows.length+'件。未収録は圏外を意味しません。'};[search,provider,subject,year].forEach(n=>n.addEventListener('input',render));render();}
 const directory=document.getElementById('directoryList');
 if(directory){const data=window.GERMANY_UNIVERSITIES||{cities:[],universities:[]},cities=new Map(data.cities.map(c=>[c.id,c])),search=document.getElementById('directorySearch'),mode=document.getElementById('directoryMode');const render=()=>{const q=search.value.trim().toLowerCase();const rows=data.universities.filter(u=>{const c=cities.get(u.cityId)||{};return [u.name,c.name,c.state].join(' ').toLowerCase().includes(q)&&(mode.value!=='guide'||u.guideUrl)&&(mode.value!=='student'||u.studentIds?.length)});directory.replaceChildren();for(const u of rows){const c=cities.get(u.cityId)||{},b=el('article',undefined,'directoryItem');b.append(el('h3',u.name),el('p',[c.name,c.state].filter(Boolean).join(' / ')),a(u.sourceUrl,'公式出典 ↗'));if(u.guideUrl)b.append(document.createTextNode('　'),a(u.guideUrl,'大学ガイド'));for(const id of u.studentIds||[])b.append(document.createTextNode('　'),a('index.html#student-'+id,'現役生を見る'));directory.append(b)}document.getElementById('directoryCount').textContent=rows.length+'件を表示';};[search,mode].forEach(n=>n.addEventListener('input',render));render();}
 document.querySelectorAll('[data-news-list]').forEach(container=>{const official=(window.GERMANY_NEWS?.items||[]).map(i=>({...i}));const columns=(window.GERMANY_COLUMNS||[]).filter(i=>i.enabled===true).map(i=>({title:i.title,date:i.date,url:i.url,category:'現役生コラム'}));const own=(window.GERMANY_UPDATES||[]).filter(i=>i.enabled!==false);const today=new Date().toISOString().slice(0,10);const rows=[...own,...columns,...official].filter(i=>i.date<=today).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);container.replaceChildren();for(const i of rows){const b=el('article',undefined,'newsItem');const date=el('time',i.date+' / '+i.category);date.dateTime=i.date;b.append(date,a(i.url,i.title));container.append(b)}if(!rows.length)container.append(el('p','新しいお知らせを準備しています。'));});
})();
